name       : liblastfm
version    : 1.1.0
release    : 2
source     :
    - https://github.com/lastfm/liblastfm/archive/refs/tags/1.1.0.tar.gz : f61f0daa384e081a8f2bd2f7a2148babff22696e5b72ecdac86940a10100b1c8
license    : GPL-3.0
component  : programming.library
summary    : A Qt C++ library for the Last.fm webservices
description: |
    A Qt C++ library for the Last.fm webservices
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
setup      : |
    %patch -p1 < $pkgfiles/liblastfm-qt5.11.patch
    %cmake \
      -DCMAKE_CXX_STANDARD=14 \
      -DBUILD_TESTS=OFF .
build      : |
    %make
install    : |
    %make_install
