name       : liblastfm
version    : 1.0.9
release    : 1
source     :
    - https://github.com/lastfm/liblastfm/archive/1.0.9.tar.gz : 5276b5fe00932479ce6fe370ba3213f3ab842d70a7d55e4bead6e26738425f7b
license    : GPL-3.0
component  : programming.library
summary    : A Qt C++ library for the Last.fm webservices
description: |
    A Qt C++ library for the Last.fm webservices
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
